/* Used as starting data for ShopPage */

const SHOP_DATA = [
  {
    id: 1,
    title: 'Hats',
    routeName: 'hats',
    items: [
      {
        id: 1,
        name: 'Brown Brim',
        // imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        imageUrl: 'hats/brown-brim',
        price: 25,
      },
      {
        id: 2,
        name: 'Blue Beanie',
        // imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
        imageUrl: 'hats/blue-beanie',
        price: 18,
      },
      {
        id: 3,
        name: 'Brown Cowboy',
        // imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
        imageUrl: 'hats/brown-cowboy',
        price: 35,
      },
      {
        id: 4,
        name: 'Grey Brim',
        // imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
        imageUrl: 'hats/grey-brim',
        price: 25,
      },
      {
        id: 5,
        name: 'Green Beanie',
        // imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
        imageUrl: 'hats/green-beanie',
        price: 18,
      },
      {
        id: 6,
        name: 'Palm Tree Cap',
        // imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
        imageUrl: 'hats/palm-tree-cap',
        price: 14,
      },
      {
        id: 7,
        name: 'Red Beanie',
        // imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
        imageUrl: 'hats/red-beanie',
        price: 18,
      },
      {
        id: 8,
        name: 'Wolf Cap',
        // imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
        imageUrl: 'hats/wolf-cap',
        price: 14,
      },
      {
        id: 9,
        name: 'Blue Snapback',
        // imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
        imageUrl: 'hats/blue-snapback',
        price: 16,
      },
    ],
  },
  {
    id: 2,
    title: 'Sneakers',
    routeName: 'sneakers',
    items: [
      {
        id: 10,
        name: 'Adidas NMD',
        // imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
        imageUrl: 'sneakers/adidas-nmd',
        price: 220,
      },
      {
        id: 11,
        name: 'Adidas Yeezy',
        // imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
        imageUrl: 'sneakers/yeezy',
        price: 280,
      },
      {
        id: 12,
        name: 'Black Converse',
        // imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
        imageUrl: 'sneakers/black-converse',
        price: 110,
      },
      {
        id: 13,
        name: 'Nike White AirForce',
        // imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
        imageUrl: 'sneakers/white-nike-high-tops',
        price: 160,
      },
      {
        id: 14,
        name: 'Nike Red High Tops',
        // imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
        imageUrl: 'sneakers/nikes-red',
        price: 160,
      },
      {
        id: 15,
        name: 'Nike Brown High Tops',
        // imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
        imageUrl: 'sneakers/nike-brown',
        price: 160,
      },
      {
        id: 16,
        name: 'Air Jordan Limited',
        // imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
        imageUrl: 'sneakers/nike-funky',
        price: 190,
      },
      {
        id: 17,
        name: 'Timberlands',
        // imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
        imageUrl: 'sneakers/timberlands',
        price: 200,
      },
    ],
  },
  {
    id: 3,
    title: 'Jackets',
    routeName: 'jackets',
    items: [
      {
        id: 18,
        name: 'Black Jean Shearling',
        // imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
        imageUrl: 'jackets/black-shearling',
        price: 125,
      },
      {
        id: 19,
        name: 'Blue Jean Jacket',
        // imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
        imageUrl: 'jackets/blue-jean-jacket',
        price: 90,
      },
      {
        id: 20,
        name: 'Grey Jean Jacket',
        // imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
        imageUrl: 'jackets/grey-jean-jacket',
        price: 90,
      },
      {
        id: 21,
        name: 'Brown Shearling',
        // imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
        imageUrl: 'jackets/brown-shearling',
        price: 165,
      },
      {
        id: 22,
        name: 'Tan Trench',
        // imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
        imageUrl: 'jackets/brown-trench',
        price: 185,
      },
    ],
  },
  {
    id: 4,
    title: 'Womens',
    routeName: 'womens',
    items: [
      {
        id: 23,
        name: 'Blue Tanktop',
        // imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
        imageUrl: 'womens/blue-tank',
        price: 25,
      },
      {
        id: 24,
        name: 'Floral Blouse',
        // imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
        imageUrl: 'womens/floral-blouse',
        price: 20,
      },
      {
        id: 25,
        name: 'Floral Dress',
        // imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
        imageUrl: 'womens/floral-skirt',
        price: 80,
      },
      {
        id: 26,
        name: 'Red Dots Dress',
        // imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
        imageUrl: 'womens/red-polka-dot-dress',
        price: 80,
      },
      {
        id: 27,
        name: 'Striped Sweater',
        // imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
        imageUrl: 'womens/striped-sweater',
        price: 45,
      },
      {
        id: 28,
        name: 'Yellow Track Suit',
        // imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
        imageUrl: 'womens/yellow-track-suit',
        price: 135,
      },
      {
        id: 29,
        name: 'White Blouse',
        // imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
        imageUrl: 'womens/white-vest',
        price: 20,
      },
    ],
  },
  {
    id: 5,
    title: 'Mens',
    routeName: 'mens',
    items: [
      {
        id: 30,
        name: 'Camo Down Vest',
        // imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
        imageUrl: 'mens/camo-vest',
        price: 325,
      },
      {
        id: 31,
        name: 'Floral T-shirt',
        // imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
        imageUrl: 'mens/floral-shirt',
        price: 20,
      },
      {
        id: 32,
        name: 'Black & White Longsleeve',
        // imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
        imageUrl: 'mens/long-sleeve',
        price: 25,
      },
      {
        id: 33,
        name: 'Pink T-shirt',
        // imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
        imageUrl: 'mens/pink-shirt',
        price: 25,
      },
      {
        id: 34,
        name: 'Jean Long Sleeve',
        // imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
        imageUrl: 'mens/roll-up-jean-shirt',
        price: 40,
      },
      {
        id: 35,
        name: 'Burgundy T-shirt',
        // imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
        imageUrl: 'mens/polka-dot-shirt',
        price: 25,
      },
    ],
  },
];

export default SHOP_DATA;
